In [13]:
import segmentation
import pickle
import os
import numpy as np
from keras.models import load_model
from collections import Counter


with open('i2t.pickle', 'rb') as handle1:
    sen_label_i2t = pickle.load(handle1)
with open('t2i.pickle', 'rb') as handle2:
    sen_label_t2i = pickle.load(handle2)

    
sen_label = []
sen_data = []
sen_class_path = 'sentence_dataset/'
for i in os.listdir(sen_class_path):
    sen_image_path = sen_class_path + str(i) + '/'
    for j in os.listdir(sen_image_path):
        sen_label.append(sen_label_t2i[i])
        img = segmentation.CharSeg(sen_image_path, j, (58, 58))
        sen_data.append(img.run())
print('done')

done


In [14]:
print(len(sen_data))
for i in sen_label:
    print(i)
    print(sen_label_i2t[i])

1120
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
22
阅读文章 诗歌鉴赏
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
32
新闻 体育
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
44
萌宠
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
26
医疗健康 生育
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
3
购物 美妆
13
购物 生鲜食品
13
购物 生鲜食品
13
购物 生鲜食品
13
购物 生鲜食品
13
购物 生鲜食品


25
生活服务 法律咨询
25
生活服务 法律咨询
25
生活服务 法律咨询
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
55
新闻 汽车
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
38
资讯 会记税收
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
0
生活服务 摄影
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
9
博彩
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
12
购物 手机
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
28
购物 奢侈品
2

In [15]:
import tensorflow as tf 
import math

def conv(x_):
    conv1 = tf.layers.conv2d(
            inputs=x_,
            filters=32,  # number of filters
            kernel_size=[5, 5],
            padding="same",
            activation=tf.nn.relu)
    
    pool1 = tf.layers.max_pooling2d(inputs=conv1, 
                                    pool_size=[2, 2], 
                                    strides=2)  # convolution stride
    
    conv2 = tf.layers.conv2d(
            inputs=pool1,
            filters=64, # number of filters
            kernel_size=[5, 5],
            padding="same",
            activation=tf.nn.relu)
    
    pool2 = tf.layers.max_pooling2d(inputs=conv2, 
                                    pool_size=[2, 2], 
                                    strides=2)  # convolution stride
    conv3 = tf.layers.conv2d(
            inputs=pool2,
            filters=128, # number of filters
            kernel_size=[5, 5],
            padding="same",
            activation=tf.nn.relu)
    
    pool3 = tf.layers.max_pooling2d(inputs=conv3, 
                                    pool_size=[2, 2], 
                                    strides=2)  # convolution stride
    conv4 = tf.layers.conv2d(
            inputs=pool3,
            filters=256, # number of filters
            kernel_size=[5, 5],
            padding="same",
            activation=tf.nn.relu)
    
    pool4 = tf.layers.max_pooling2d(inputs=conv4, 
                                    pool_size=[2, 2], 
                                    strides=1)  # convolution stride
    conv5 = tf.layers.conv2d(
            inputs=pool4,
            filters=512, # number of filters
            kernel_size=[5, 5],
            padding="same",
            activation=tf.nn.relu)
    
    pool5 = tf.layers.max_pooling2d(inputs=conv5, 
                                    pool_size=[2, 2], 
                                    strides=1)  # convolution stride
    
    pool_flat = tf.contrib.layers.flatten(pool5, scope='pool2flat')
    dense = tf.layers.dense(inputs=pool_flat, units=5000, activation=tf.nn.relu)
    logits = tf.layers.dense(inputs=dense, units=3755)
    return logits


def classification(model_function):
    with tf.Graph().as_default() as g:
        with tf.device("/cpu:0"):  # use gpu:0 if on GPU
            x_ = tf.placeholder(tf.float32, [None, 58, 58, 3])
            drop_out = tf.placeholder(tf.float32)
            y_logits = model_function(x_)
            y_pred = tf.argmax(tf.nn.softmax(y_logits), axis=1)
    model_dict = {'graph': g, 'inputs': [x_], 'prediction': y_pred}
    
    return model_dict

def get_pred(xte):
    with model_dict['graph'].as_default(), tf.Session() as sess:
        sess.run(tf.global_variables_initializer())
        saver = tf.train.Saver()
        saver.restore(sess, 'checkpoints3755/checkpoint.ckpt')
        sen_s = []
        for i in range(len(xte)):
            sen_data = xte[i]
            test_feed_dict = dict(zip(model_dict['inputs'], [sen_data]))
            to_compute = [model_dict['prediction']]       
            result = sess.run(to_compute, test_feed_dict)
            sen_s.append(result)
        return sen_s
    
model_dict = classification(conv)
sen_s = get_pred(sen_data)
print('done')

INFO:tensorflow:Restoring parameters from checkpoints3755/checkpoint.ckpt
done


In [16]:
sen_s_array = np.array(sen_s)

with open('sens.pickle', 'wb') as handle1:
    pickle.dump(sen_s_array, handle1, protocol=pickle.HIGHEST_PROTOCOL)

In [17]:
with open('c2n.pickle', 'rb') as handle1:
    char_label_c2n = pickle.load(handle1)
with open('n2c.pickle', 'rb') as handle2:
    char_label_n2c = pickle.load(handle2)
    
print(sen_s[0])

[array([1536,  750, 3379, 1775, 2962, 2813, 2342, 1560, 3095, 3326,  846,
       2813, 3095,  287, 3379, 1775,  842, 3502, 2638,   34,  815])]


In [18]:
sens_in_char = []

for sen in sen_s:
    sen_in_char = ''
    for i in sen [0]:
        sen_in_char = sen_in_char + str(char_label_n2c[i])
    sens_in_char.append(sen_in_char)
print(sens_in_char[0])

春天郭毅蚕节短暂诗选季节诗况郭毅孙闭罐丽娟


In [19]:
import jieba

sens_in_words = []
for sen in sens_in_char:
    text1 = sen
    seg_list = jieba.cut(text1, cut_all=False)
    array1 = []
    array1.append(",".join(seg_list))
    array2 = []
    for i in range(len(array1)):
        array2.append(array1[i].split(","))

    while '' in array2[0]:
        array2[0].remove('')
    sens_in_words.append(array2[0])
    
for i in sens_in_words:
    print(i)
# print(sen_label)

['春天', '郭毅', '蚕节', '短暂', '诗选', '季节', '诗况', '郭毅', '孙闭', '罐丽娟']
['孙', '梅苏', '文华', '诗选', '短暂', '月伦', '曹树莹', '苏文毕', '郭毅王', '玉兰', '季节']
['诵读', '世彤', '诵读', '记忆', '就是', '星雀', '诵读', '天', '旅行', '世界']
['旅行', '天山路', '世界', '想着', '这样', '天', '就是', '就是', '记忆']
['屈厚', '涣', '稠', '韦蜘花开', '评论', '屈原', '散文', '詹芳珍', '母亲节']
['花', '开', '油画', '散文', '郑周', '吞燕', '平尔山', '张永强', '特刊', '郑', '中国']
['今天', '英语', '塞下曲', '诵读', '怀古', '诗文', '浪淘沙', '快乐', '歉为', '及', '外']
['涂鸦', '乐天', '塞下曲', '早春', '塞下曲', '塞下曲', '悠闲', '亲子', '快乐', '涂鸦']
['散文', '江南', '两首', '随笔', '江南', '江南', '散文', '诗歌', '诗歌', '诗歌']
['江南', '谆歌', '丙首', '节气', '诗歌', '江南', '随笔', '诗歌', '随笔', '两首']
['成洲', '快空', '成议', '川', '立冬', '黑波', '成洲', '声音', '季芦', '袄', '声音']
['季节', '成洲', '云层', '减洲', '热度', '孩子', '云层', '呼吸', '时回', '成洲']
['长桥', '山谷', '山谷', '札记', '来信', '白山', '寂静', '活动', '无用', '创作']
['专辑', '无用', '当是', '森詹事', '寂静', '虚构', '趣闸', '纪实', '中篇']
['诗选', '寂静', '黄河', '寂静', '寂静', '赤水河', '文选', '赤水河', '文选', '飞云', '江']
['顽石', '黄河', '如何', '顽石', '寂静', '如付', '名字', '诗选', '文选', '飞云', '江']
[

In [20]:
from keras.models import load_model

class Predict_labels:
    def __init__(self):
        self.model = load_model('model_textcnn_detection.h5')
        self.model.load_weights('model.weights.best.hdf5')
#         with open('i2t.pickle', 'rb') as handle:
#             self.int_to_targets = pickle.load(handle)
#         with open('v2i.pickle', 'rb') as handle:
#             self.vocab_to_int = pickle.load(handle)
#         stop_words_file = open('stopword.txt')
#         self.stopwords = set([item.strip('\n') for item in stop_words_file])
        self.special_sign = set(['',' ','\u3000','｜','一','…','丨','←'])
    def make_classification(self,text):
#         text_int = [self.vocab_to_int[word] if word in self.vocab_to_int else 0 for word in text.split()]
#         seq_len = 10
#         feature = np.zeros(seq_len, dtype=int)
#         counts = Counter(text_int)
#         row = sorted(text_int, key = lambda x : counts[x], reverse=True)
#         if(len(row) == 0):
#             return 'none'
#         feature[-len(row):] = np.array(row)[:seq_len]
#         print(text[None,:])
        label = self.model.predict(text)
        pred = np.argmax(label,axis = 1)
        
        return pred


In [21]:
sens_in_int_list = []
with open('i2t.pickle', 'rb') as handle:
    int_to_targets = pickle.load(handle)
with open('v2i.pickle', 'rb') as handle:
    vocab_to_int = pickle.load(handle)

for sen in sens_in_words:
    text_int = [vocab_to_int[word] if word in vocab_to_int else 0 for word in sen]
#     print(len(text_int))
    seq_len = 10
    feature = np.zeros(seq_len, dtype=int)
    counts = Counter(text_int)
    row = sorted(text_int, key = lambda x : counts[x], reverse=True)
    feature[-len(row):] = np.array(row)[:seq_len]
    sens_in_int_list.append(feature)
sens_in_int = np.array(sens_in_int_list)
print(sens_in_int)
#     sen
#     print(feature)
    

[[    0     0     0 ...  6043  9960 44851]
 [    0     0     0 ...  9960  6043 34933]
 [10161     0 10161 ... 30308 27071 26780]
 ...
 [    0     0     0 ... 27723 29362 33011]
 [    0     0 44419 ... 29560 26443 28139]
 [    0     0     0 ... 45803  2896  5648]]


In [22]:
# for sen in sens_in_words:
# a = '装饰,英德,分公司,工程,案例,半岛,恭贺,芙蓉,春晓,刘先生,开工,恭贺,芙蓉,春晓,刘先生,开工,装饰,英德,分公司,工程,案例,中医院,入口,门楼,装饰,英德,分公司,工程,案例,中医院,入口,门楼,恭贺,开工,装饰,案例,这样,自己,装修,房子,装修,通知,装修,涨价,已成,定局,躲开,装修,涨价,聪明,花都,房主,这样,恭贺,桔子,水晶,酒店,酒庄,开工,装修,通知,装修,涨价,已成,定局,躲开,装修,涨价,聪明,花都,房主,这样,恭贺,桔子,水晶,酒店,酒庄,开工,装饰,英德,分公司,工装,案例,办公室,装饰,装饰,快乐,北欧,家居,搭配,简单,装修,设计,案例,工作,地下,设计,卧室,设计,客厅,工作,整装,北欧,印象,装饰,设计,如何,装修,装饰,低价,整装,套餐,家居,装饰,设计,无法,拒绝,装饰,设计,公司,招聘,启事,认真,装饰,设计,恭贺,贵府,开工,装修,装饰,设计,公司,招聘,启事,认真,装饰,设计,公司,招聘,启事,认真,装饰,设计,装饰,公司,装饰,设计,公司,招聘,启事,认真,装饰,设计,中国,装饰,设计,中国,装饰,设计,恭贺,公司,开工,装饰,设计,恭贺,半岛,开工,装饰,设计,每周,工地,巡查,装饰,书房,无法,拒绝,装饰,设计,每周,工地,巡查,装饰,装饰,装修,值得,值得,花钱,地方,知道,装饰,设计,每周,工地,巡查,装饰,设计,恭贺,芙蓉,春晓,刘先生,贵府,开工,装修,这些,知道,装饰,设计,每周,工地,巡查,可以,知道,装饰,阳台,可以,赶紧,礼物,其实,装饰,设计,装饰,设计,每周,工地,巡查,装饰,设计,卫生间,流行,这样,装饰,设计,每周,工地,巡查,装饰,设计,吊顶,原来,可以,这么,装饰,设计,每周,工地,巡查,低价,同行,自己,装饰,设计,每周,工地,巡查,快乐,还是,装饰,设计,每周,工地,巡查,装饰,设计,恭贺,春晓,开工,装饰,设计,恭贺,春晓,开工,装饰,设计,每周,工地,巡查,窗帘,这样,搭配,房间,装饰,设计,每周,工地,巡查,生活,技巧,卧室,利用,实用,厨房,装饰,设计,每周,工地,巡查,这样,设计,实用,装饰,设计,恭贺,开工,房间,这些,利用,原来,这么,装修,厨房,为什么,设计,卧室,书房,如何,设计,流行,装饰,英德,分公司,工装,案例,展示,整体,家装,套餐,案例,恭贺,开工,装饰,英德,分公司,工装,案例,办公室,装饰,设计,恭贺,雅居乐,贵府,开工,花都,装饰,设计,整装,套餐,整装,套餐,整装,套餐,装饰,套餐,空间,装饰,套餐,装饰,英德,分公司,工装,案例,生活,其实,设计,空间,家里,装修,吊顶,整体,家装,套餐,案例,恭贺,时代,贵府,开工,装饰,整装,套餐,印象,装饰,整装,套餐,时代,装饰,整装,套餐,装饰,整装,套餐,装饰,整装,套餐,装饰,整装,套餐,装饰,整装,套餐,礼物,装修,赶紧,花钱,家里,客厅,装修,细节,知道,装饰,设计,恭贺,花园,贵府,开工,装饰,如何,客厅,还是,什么,装修,注意,技巧,细节,装饰,设计,恭贺,开工,花都,同行,窗帘,这样,颜值,家里,这些,装饰,设计,恭贺,雅居乐,开工,水上,建筑,建筑,水上,花都,样子,生活,样子,装饰,英德,分公司,工装,案例,展示,广西,贵港,地下,商城,装饰,英德,分公司,工装,案例,展示,广西,贵港,地下,商城,厨房,实用,什么,家里,喜欢,北欧,这么,简单,阳台,装饰,设计,恭贺,万达,雪域,澜庭,开工,装饰,设计,恭贺,别墅,开工,房子,地方,卫生间,颜值,装饰,设计,恭贺,万达,雪域,澜庭,开工,整体,家装,套餐,案例,恭贺,花园,贵府,开工,为什么,鞋柜,这些,鞋柜,设计,喜欢,装修,装修,装修,注意,什么,案例,别墅,其实'
# pred_in_char = p.make_classification(a)
# print(pred_in_char)
# print(sen_label_w2n[pred_in_char])
p = Predict_labels()
# input_str = ''
# sen_label_pred = []

# pred_in_char = p.make_classification()




# for sen in sens_in_words:
# for word in sens_in_words[100]:
#     input_str += word
#     input_str += ' '
# temp = input_str
# for i in range(10):
#     input_str += temp
pred_in_char = p.make_classification(sens_in_int)
# sen_label_pred.append(sen_label_t2i[pred_in_char])
# print(len(pred_in_char[0]))

# print(sen_label_2t[pred_in_char])
# print(sen_label_n2w[])
# n = 0    

In [23]:
for i in range(len(pred_in_char)):
    print(pred_in_char[i]- sen_label[i])

0
0
19
20
17
-22
-17
17
0
13
29
14
17
11
17
29
20
20
29
19
0
0
0
0
-16
0
10
0
0
-31
10
0
3
3
0
0
0
0
0
0
-2
-26
-44
-2
0
-11
-17
-7
-12
0
-12
0
-5
6
0
-17
0
-44
-44
-2
0
8
21
0
0
7
0
17
21
0
6
-23
11
24
0
1
0
-25
0
7
30
-3
0
-2
0
-3
0
0
24
0
39
48
0
0
34
11
0
0
-3
16
11
26
29
29
30
37
-8
0
1
-13
0
0
0
28
0
11
1
1
0
23
0
23
-10
0
0
0
18
13
18
0
17
-10
0
3
0
6
0
0
0
0
-41
-41
0
0
0
-17
0
0
9
0
0
0
0
0
0
-3
0
0
0
0
-9
0
-14
-4
0
6
-3
-40
0
-5
0
0
-7
-7
-7
-14
0
0
0
0
0
8
0
0
0
-5
0
0
0
0
-26
0
-37
5
2
0
0
-30
-4
0
0
0
32
32
-2
0
0
-2
0
20
0
0
0
35
35
9
2
0
0
0
0
0
0
0
0
0
0
0
0
0
25
0
0
0
23
0
0
36
0
0
-9
-9
-46
-46
0
-18
-10
0
-51
0
0
0
0
0
-10
-10
0
-50
0
0
8
-17
0
8
0
8
21
0
-31
0
0
8
-23
-8
8
0
-31
0
0
-24
0
0
0
0
0
0
0
0
0
-11
0
0
12
0
0
26
0
0
0
0
0
0
0
0
0
35
18
18
47
24
29
45
0
0
39
0
0
37
0
0
4
-34
0
0
-3
-2
0
16
0
0
0
0
0
-13
0
0
0
0
-3
0
23
32
0
32
0
0
29
0
0
-18
0
0
-19
-10
-19
-19
0
-8
-8
0
42
44
19
-7
34
44
34
0
-7
31
29
25
31
-7
44
44
0
34
25
0
6
-3
0
0
0
3
0
-35
3
0
-35
0


In [24]:
n = 0
for i in range(len(pred_in_char)):
    if sen_label[i] == pred_in_char[i]:
        n = n+1
accuracy = n/len(sen_label)
print(accuracy)

0.4589285714285714


In [19]:
print(sens_in_words[0])
# print(sen_label_n2w[sen_label[51]])

['诗选', '诗选', '诗选', '诗选', '诗选', '春天', '周伦', '诗选', '诗选', '诗选']


KeyError: 9

In [1]:
# temp_dic = {}
# with open('i2t.pickle', 'rb') as handle:
#     temp_dic = pickle.load(handle)
# sen_label = []
# sen_data = []
for i in range(len(sen_label)):
    if sen_label[i] == 23:
        print(sens_in_words[i])

# with open('i2t.pickle', 'rb') as handle2:
#     temp_dic2 = pickle.load(handle2)
# print(temp_dic2)

NameError: name 'sen_label' is not defined